支援艦隊の遠征を出した際に非通知にできるようにする
KanCraft/kanColleWidget pull request #1228
Opened 2020-10-05 04:00 UTC by moriyadetteiu

fix: #1221

## 設定画面UI
ID入力欄と連動するプルダウンを用意することで基本的にはIDを意識しなくても使えるつくりにし、 [missions.ts](https://github.com/KanCraft/kanColleWidget/blob/develop/src/js/Applications/Models/Queue/missions.ts) に未登録の場合にのみ遠征に出した際のID値を参照するような形にした。
とりあえず最初から入力欄も出る形にしたが、隠しておいてボタンを押したら出てくるようなUIでもいいかも。
![t](https://user-images.githubusercontent.com/8841932/95038508-434aae80-0709-11eb-834e-845c1806b228.gif)

## 確認事項
 - [ ] 登録 / 更新 / 削除が可能
![t](https://user-images.githubusercontent.com/8841932/95038881-2793d800-070a-11eb-9308-f78d8cfccf55.gif)

 - [ ] 初期化が可能
![t](https://user-images.githubusercontent.com/8841932/95038906-37132100-070a-11eb-9be6-8ce2331b049f.gif)

 - [ ] 非通知設定に応じて、通知の発火が制御されている
![t](https://user-images.githubusercontent.com/8841932/95038978-64f86580-070a-11eb-9d97-7adbe0bdd6e1.gif)

## カタログについて
（すでにご存じかもしれないですが）艦これのページにアクセスしたときにマスタを取りに行くAPI叩いてるみたいなので、アクセスごとにlocalStorageに格納して更新するみたいなことも可能ではあるかもです。
![2020-10-05_120055](https://user-images.githubusercontent.com/8841932/95039043-a557e380-070a-11eb-8520-86c3f322d466.png)

## 一言
微妙なところとかは突っ込んでいただけると助かります。

2020-10-05 04:52 UTC, otiai10 reviewed
ありがとうございます。何点かコメントさせていただきました。
勉強させていただきます！

2020-10-05 04:52 UTC, otiai10 commented on src/js/Applications/Components/Options/DisableMissionNotificationSettings/index.tsx
> +class UnknownMissionHelp extends React.Component <{}, {
`UnknownMissionHelp` は、ソースコードとしてはオーバーキルかなと感じました。wikiのページに寄せていくのがいいかなと。

2020-10-05 04:52 UTC, otiai10 commented on src/js/Applications/Components/Options/index.tsx
> +        <DisableMissionNotificationSettingView />
UI的には、`NotificationSettings` の小項目かと思ったのですが、いかがでしょうか

2020-10-05 04:52 UTC, otiai10 commented on src/js/Applications/Models/Settings/DisableMissionNotificationSetting.ts
> +  static hasMissionId(missionId: number | string): boolean {
`static default` 値も含めて、id == missionIDという構造にすれば、`hasMissionId`を追加する必要は無いかなと思います。

```js
static default = {
  "33": { /* title: xxx */ },
  "34": { /* title: xxx */ },
  "197": { /* title: xxx */ },
  "198": { /* title: xxx */ },
}
```

としておけば、`hasMissionId`の代わりに

```js
const found = DisableMissionNotificationSetting.find(missionId);
```

で事が済むかなと。なお、`chomex.Model.new`かなんかに、`_id`を指定してconstructするメソッドがあったはずです。うろ覚えですが...

2020-10-05 04:52 UTC, otiai10 commented on src/js/Applications/Background/Controllers/Request/Mission.ts
> +  if (!mission.shouldNotify()) {
ここは、`Mission`モデルに`shouldNotify`を生やすよりは、`DisableMissionNotificationSetting.find`を使うのがstraightforwardだと思います。KISSです。

2020-10-05 04:52 UTC, otiai10 commented on src/js/Applications/Components/Options/DisableMissionNotificationSettings/index.tsx
> +  missions: mission[]
ここは逆に`Mission`モデルの[]でいいかなと感じました。`Mission.for`が使えると思います。なので、

https://github.com/KanCraft/kanColleWidget/pull/1228/files#diff-0c919453d8cc92138f722faecb91618fR31

は

```js
.map(id => Mission.for(id, 0));
```

みたいな感じをイメージしています。
この場合Modelがmutableというリスクはありますが、simple codeのほうが優先かなと考えています。

2020-10-05 04:57 UTC, otiai10 commented on src/js/Applications/Components/Options/DisableMissionNotificationSettings/index.tsx
> +  missions: mission[]
mutabilityのコントロールと言う意味では、持ち方としてはinterfaceの[]でいいかもしれないですね。

2020-10-05 04:59 UTC, otiai10 commented
> 艦これのページにアクセスしたときにマスタを取りに行くAPI叩いてるみたいなので、アクセスごとにlocalStorageに格納して更新するみたいなことも可能ではあるかもです。

この点に関しては、HTTPのresponseをChrome拡張から覗けない、という障壁があったと思います。これもうろ覚えなんですが...

2020-10-07 11:00 UTC, moriyadetteiu commented on src/js/Applications/Components/Options/DisableMissionNotificationSettings/index.tsx
> +class UnknownMissionHelp extends React.Component <{}, {
確かにwikiに書いたほうがすっきりですし、メンテナンス性よさそうですね。
[wiki](https://github.com/KanCraft/kanColleWidget/wiki/%E8%89%A6%E3%81%93%E3%82%8C%E3%82%A6%E3%82%A3%E3%82%B8%E3%82%A7%E3%83%83%E3%83%88%E3%81%AE%E4%BD%BF%E3%81%84%E6%96%B9) に記載する際には `艦これウィジェットのUI` の項目にぶら下げる形で `オプション` のセクション切るのがよさそうでしょうか？

2020-10-07 11:37 UTC, moriyadetteiu commented on src/js/Applications/Models/Settings/DisableMissionNotificationSetting.ts
> +  static hasMissionId(missionId: number | string): boolean {
@otiai10 
create, deleteのみの構造であれば `_id` に入れるのがシンプルそうですが、updateをすることも考えると `_id` の値が変更される場合、 `save` メソッド等が機能しなくなってしまうのが気になります。
https://github.com/otiai10/chomex/blob/54d0f7597d4c89f5a72ad3f78f08aed3f06b591b/src/Model/index.ts#L212-L221

findで処理できること自体は魅力的なので、やるのであれば `DisableMissionNotificationSetting` に `findByMissionId` みたいなのをはやす感じでしょうか？

2020-10-07 11:39 UTC, moriyadetteiu commented on src/js/Applications/Background/Controllers/Request/Mission.ts
> +  if (!mission.shouldNotify()) {
https://github.com/KanCraft/kanColleWidget/pull/1228#discussion_r500941625 でコメントしたように、 `find` で実装する問題点をどうするか悩ましい感じです。 `shouldNotify` メソッドをはやすこと自体は確かに冗長ではあるので、直接 `DisableMissionNotificationSetting` を叩くようにしたいようであれば、変更します！

2020-10-07 11:40 UTC, otiai10 commented on src/js/Applications/Components/Options/DisableMissionNotificationSettings/index.tsx
> +class UnknownMissionHelp extends React.Component <{}, {
`艦これウィジェットの使い方 / 基本的な機能の使い方 / 遠征終了通知`
というセクションを作ったので、ここではどうでしょう
https://github.com/KanCraft/kanColleWidget/wiki/%E8%89%A6%E3%81%93%E3%82%8C%E3%82%A6%E3%82%A3%E3%82%B8%E3%82%A7%E3%83%83%E3%83%88%E3%81%AE%E4%BD%BF%E3%81%84%E6%96%B9#%E9%81%A0%E5%BE%81%E7%B5%82%E4%BA%86%E9%80%9A%E7%9F%A5

2020-10-07 11:44 UTC, otiai10 commented on src/js/Applications/Models/Settings/DisableMissionNotificationSetting.ts
> +  static hasMissionId(missionId: number | string): boolean {
`_id`が変更されるケースってどういうケースですか？

2020-10-07 11:45 UTC, moriyadetteiu commented on src/js/Applications/Components/Options/DisableMissionNotificationSettings/index.tsx
> +class UnknownMissionHelp extends React.Component <{}, {
ご対応ありがとうございます！
記入させていただきます。

2020-10-07 12:16 UTC, moriyadetteiu commented on src/js/Applications/Models/Settings/DisableMissionNotificationSetting.ts
> +  static hasMissionId(missionId: number | string): boolean {
@otiai10 
![image](https://user-images.githubusercontent.com/8841932/95329618-303f0680-08e2-11eb-838e-bb3bb1a5566a.png)
上記画像のように、設定済みの遠征IDを編集する際ですね。
いっそのこと、UI的に編集は不可にして、登録/削除のみにするという手もありかとは思います。

2020-10-07 12:19 UTC, moriyadetteiu commented on src/js/Applications/Components/Options/index.tsx
> +        <DisableMissionNotificationSettingView />
ご指摘ありがとうございます！
こちら対応致しました。

2020-10-07 12:24 UTC, otiai10 commented on src/js/Applications/Models/Settings/DisableMissionNotificationSetting.ts
> +  static hasMissionId(missionId: number | string): boolean {
おっしゃる通り_idは不変であるべきなので、登録後の編集、とくに遠征IDの編集は無くて良いかと思いました。

2020-10-07 12:38 UTC, moriyadetteiu commented on src/js/Applications/Components/Options/DisableMissionNotificationSettings/index.tsx
> +  missions: mission[]
ご指摘ありがとうございます。
ないとは思いますが、何かしらの手違いで `save` メソッド呼ばれるなどのバグが混入しえる面もありますし、interface[]のほうがいいかと考えております。
そこまで強い意見ではないので、 `Mission` を使うように所望されるようであれば、修正いたします。

2020-10-07 12:39 UTC, moriyadetteiu commented on src/js/Applications/Models/Settings/DisableMissionNotificationSetting.ts
> +  static hasMissionId(missionId: number | string): boolean {
承知いたしました。
では、登録後は削除のみ可能という形で対応させていただきます！

2020-10-07 13:38 UTC, otiai10 commented on src/js/Applications/Components/Options/DisableMissionNotificationSettings/index.tsx
> +  missions: mission[]
constructには`Mission.for`を使うが、_idとtitleのみを持つinterfaceを定義するのがいいと思います。具体的には、

```js
class DisableMissionNotificationEditor extends React.Component <{
  // ...
}, {
  // ...
  missions: { _id: number; title: string; }[];
```

でよいかと思います。TypeScript的には`save`など利用不可になるので。

2020-10-07 13:39 UTC, moriyadetteiu commented
@otiai10 
こちらレビューいただいた分、修正いたしましたので、お時間あるときにご確認いただけると助かります。
修正後の見た目は以下の通りになります。
![image](https://user-images.githubusercontent.com/8841932/95338485-f116b280-08ed-11eb-9ace-f351096cc4fc.png)

2020-10-07 14:21 UTC, otiai10 commented on src/js/Applications/Components/Options/Notifications/DisableMissionNotificationsSetting.tsx
> +  editMode: boolean;
`editMode`って未だに必要ですか？

2020-10-07 16:17 UTC, moriyadetteiu commented on src/js/Applications/Components/Options/DisableMissionNotificationSettings/index.tsx
> +  missions: mission[]
確かにキャストされてTypeScript側からはじけてますね、勉強になります！

2020-10-07 16:18 UTC, moriyadetteiu commented on src/js/Applications/Components/Options/Notifications/DisableMissionNotificationsSetting.tsx
> +  editMode: boolean;
そもそも修正後が違うものを無理矢理1つのクラスに詰め込んだような構造になっていたので、登録と編集でクラス分割しました。

2020-10-07 16:19 UTC, moriyadetteiu commented
追加のレビューありがとうございます！
レビューいただいた分、修正いたしましたので、お時間あるときにご確認いただけると助かります。

2020-10-09 01:27 UTC, otiai10 requested changes

2020-10-09 01:27 UTC, otiai10 commented on src/js/Applications/Components/Options/Notifications/DisableMissionNotificationsSetting.tsx
> +  missions: mission[]
```suggestion
  missions: { id: number | string, title: string }[];
```

2020-10-09 01:27 UTC, otiai10 commented on src/js/Applications/Components/Options/Notifications/DisableMissionNotificationsSetting.tsx
> +}
```suggestion
```

2020-10-09 01:27 UTC, otiai10 commented on src/js/Applications/Components/Options/Notifications/DisableMissionNotificationsSetting.tsx
> +class DisableMissionNotificationEditor extends React.Component <{
```suggestion
class DisableMissionNotification extends React.Component <{
```
Editoの権能がもう無いので

2020-10-09 01:27 UTC, otiai10 commented on src/js/Applications/Components/Options/Notifications/DisableMissionNotificationsSetting.tsx
> +                <DisableMissionNotificationEditor key={setting._id} done={() => this.refresh()} setting={setting}/>
```suggestion
                <DisableMissionNotification key={setting._id} done={() => this.refresh()} setting={setting}/>
```

2020-10-09 01:27 UTC, otiai10 commented on src/js/Applications/Components/Options/SectionTitle.tsx
> +      <ResetButton models={this.props.models}/>
❤️

2020-10-09 15:16 UTC, moriyadetteiu commented
@otiai10 
何度もご確認ありがとうございます！
ご指摘いただいた場所を修正いたしました。

2020-10-10 13:00 UTC, otiai10 approved these changes
勉強になります :bow:

2020-10-10 13:00 UTC, merged